<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <PublishReadyToRun>false</PublishReadyToRun>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <NoWarn>$(NoWarn);SYSLIB0014;SYSLIB0043;SYSLIB0045;CA1416</NoWarn>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
