<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Version>10.1</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<Company>Technitium</Company>
		<Product>Technitium DNS Server</Product>
		<Authors>Shreyas Zare</Authors>
		<AssemblyName>FailoverApp</AssemblyName>
		<RootNamespace>Failover</RootNamespace>
		<PackageProjectUrl>https://technitium.com/dns/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/TechnitiumSoftware/DnsServer</RepositoryUrl>
		<Description>Allows creating APP records in primary and forwarder zones that can return A or AAAA records, or CNAME record based on the health status of the servers. The app supports email alerts and web hooks to relay the health status.</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\DnsServerCore.ApplicationCommon\DnsServerCore.ApplicationCommon.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	
	<ItemGroup>
		<None Update="dnsApp.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

<ItemGroup>
<ProjectReference Include="..\..\..\TechnitiumLibrary\TechnitiumLibrary\TechnitiumLibrary.csproj" />
<ProjectReference Include="..\..\..\TechnitiumLibrary\TechnitiumLibrary.IO\TechnitiumLibrary.IO.csproj" />
<ProjectReference Include="..\..\..\TechnitiumLibrary\TechnitiumLibrary.Net\TechnitiumLibrary.Net.csproj" />
<ProjectReference Include="..\..\..\TechnitiumLibrary\TechnitiumLibrary.Net.Mail\TechnitiumLibrary.Net.Mail.csproj" />
</ItemGroup>
</Project>
