<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Version>5.0</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<Company>Technitium</Company>
		<Product>Technitium DNS Server</Product>
		<Authors>Shreyas Zare</Authors>
		<AssemblyName>ZoneAliasApp</AssemblyName>
		<RootNamespace>ZoneAlias</RootNamespace>
		<PackageProjectUrl>https://technitium.com/dns/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/TechnitiumSoftware/DnsServer</RepositoryUrl>
		<Description>Allows configuring aliases for any zone (internal or external) such that they all return the same set of records.</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\DnsServerCore.ApplicationCommon\DnsServerCore.ApplicationCommon.csproj">
			<Private>false</Private>
		</ProjectReference>
	</ItemGroup>

	
	<ItemGroup>
		<None Update="dnsApp.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

<ItemGroup>
<ProjectReference Include="..\..\..\TechnitiumLibrary\TechnitiumLibrary\TechnitiumLibrary.csproj" />
<ProjectReference Include="..\..\..\TechnitiumLibrary\TechnitiumLibrary.Net\TechnitiumLibrary.Net.csproj" />
</ItemGroup>
</Project>
